FROM nginx

LABEL vendor=LINKIT \
      nl.linkit.arra.is-beta="false" \
      nl.linkit.arra.is-production="true" \
      nl.linkit.arra.version="0.0.1" \
      nl.linkit.arra.release-date="01-11-2017"

COPY dist /usr/share/nginx/html
