version: '3' 

services:
  stateless:
    build: stateless

  stateful: 
    build: stateful

  frontend: 
    build: frontend
    ports:
      - "80:80" 
    links:
      - "stateless:stateless"
      - "stateful:stateful"
